name: ex 1
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: 1) Message de bienvenue
        run: echo "Bienvenue dans mon premier workflow GitHub Actions !"
      
      - name: 2) afficher la date
        run: date

      - name: 3) afficher pwd
        run: pwd

      - name: 4a) checkout code
        uses: actions/checkout@v5

      - name: 4b) lister les fichier
        run: ls -al

      - name: 5a) créer un fichier test
        run: echo "Fichier créé par GitHub Actions" > testfile.txt

      - name: 5b) vérifier que le fichier existe
        run: ls -al

      - name: 5c) afficher le contenu du fichier
        run: cat testfile.txt