name: ex 1
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: 1) Message de bienvenue
        run: echo "Bienvenue dans mon premier workflow GitHub Actions !"
      
      - name: 2) afficher la date
        run: date